# Generated by Django 3.2.16 on 2022-11-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='areas.area', verbose_name='上级⾏政区划')),
            ],
            options={
                'verbose_name': '⾏政区划',
                'verbose_name_plural': '⾏政区划',
                'db_table': 'tb_areas',
            },
        ),
    ]
