# Generated by Django 3.2.16 on 2022-12-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20221202_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='desc_detail',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='desc_pack',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='desc_service',
        ),
    ]
